### ISSUE TITLE
Released gems vs. git tags

### ISSUE THREAD

**Issue by atz** [projecthydra/om#59]
Each released gem version listed here:
   https://rubygems.org/gems/om/versions

should have a corresponding git tag in the repo.  We have 4 discrepancies.

Tags without released gems:
- `v0.0.1`
- `v1.6.2`

Gems without tags:
- `v1.7.0`
- `v1.8.0`

We probably don't need to release outdated gems, but we really should have git states tagged for releases already in the wild.  In our case, we are on `v1.8.0` and trying to backport bugfixes, but are blocked by not knowing how much changed from the RC to the gem release.  Ideally, the tags exist on an author's development version and we just need `git push --tags`.  Otherwise we need to retrace the released version to find the commit that (most closely) matches the released gem.

**Comment by atz** [comment]
OK, looks like minimal changes.  A couple commits.

```bash

om atz$ git co v1.8.0.rc1
Note: checking out 'v1.8.0.rc1'.

You are in 'detached HEAD' state. 
...
dn0a2339e6:om atz$ colordiff -r ./ ~/.rvm/gems/ruby-1.9.3-p547/gems/om-1.8.0/
...
diff -r ./History.textile /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/om-1.8.0/History.textile
0a1,10
> h3. 1.8.0
>   Removed unused mods_article_terminology.xml
>   Replacing :data_type with :type; deprecating :data_type
>   Making test related to HYDRA-647 pending
>   Adding .type method for ruby 1.8.7 compatibility
>   XML serialization should use the data_type node name and not type
>   Update homepage in gemspec
>   Remove .rvmrc
>   Remove debugger from gemfile
> 
diff -r ./lib/om/version.rb /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/om-1.8.0/lib/om/version.rb
2c2
<   VERSION = "1.8.0.rc1"
---
>   VERSION = "1.8.0"

```

**Comment by atz** [comment]
Tagging 4217e6abba21d59a13b105cc370f08152164acc3 as `v1.8.0`

**Comment by atz** [comment]
Tag pushed.   If somebody wants to do `v1.7.0`, that would be good, too.

**Comment by mjgiarlo** [comment]
:+1:

**Comment by mjgiarlo** [comment]
Created and pushed a tag for https://github.com/projecthydra/om/tree/v1.7.0, at 4454f9f31ebefff1e336a52a1d9fb6bf1ab6b8ad

**Comment by mjgiarlo** [comment]
Anything else left to do for this issue?  Thanks for raising it, @atz

**Comment by atz** [comment]
Good enough for me.
