### ISSUE TITLE
Replace textile with markdown

### ISSUE THREAD

**Issue by atz** [projecthydra/om#60]
I don't know what reasons for using the textile format might exist, but it seems like we could get a lot better rendering of the documentation pages by using Github's markdown format.  For example, look at:

https://github.com/projecthydra/om/blob/master/GETTING_FANCY.textile

Code blocks should be ruby, with color syntax highlighting, etc.  Is there anything special that we really need from textile?

**Comment by mjgiarlo** [comment]
I think the only reasons are historical, at this point, possibly even pre-GitHub. :+1: to replacing textile with markdown!

**Comment by mjgiarlo** [comment]
(And I believe pandoc can do the conversion, in part or in whole, for us automatically.)

**Comment by atz** [comment]
Pandoc conversion fails to preserve the XML code blocks.  Will take some hand retouching.

**Comment by atz** [comment]
docs can still be improved (links still broken), but conversion is done
