### ISSUE TITLE
Build and Release 1.8.1 to rubygems

### ISSUE THREAD

**Issue by atz** [projecthydra/om#67]
I committed, tagged and pushed `v1.8.1`, but I do not have access to publish to rubygems.  Please checkout, build and publish it there.  (Alternatively, authorize me to so.)

**Comment by cbeer** [comment]
@mjgiarlo what's the process here? Does @atz need to do something with https://github.com/projecthydra/hydra/blob/master/script/grant_revoke_gem_authority.rb?

**Comment by jcoyne** [comment]
@cbeer ideally, yes, add him to grant_revoke_gem_authority.rb.  To be expedient, just add him to the om owners manually.

**Comment by mjgiarlo** [comment]
@atz I'll add and authorize you. What email address is registered for you at rubygems.org?

**Comment by cbeer** [comment]
Looks like @atz has been added; I just pushed the 1.8.1 gem to rubygems.
